name: FastAPI server test

on:
  push:
    branches: [ "main" ]
    paths: ['server/**']

  pull_request:
    branches: [ "main" ]
    paths: ['server/**']

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: library_user
          POSTGRES_DB: library_test
          POSTGRES_PASSWORD: library_user
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: ./server

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev

      - name: Lint with flake8
        run: |
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          DATABASE_URL="postgresql://library_user:library_user@localhost/library_test" \
            pipenv run pytest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
